apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: mini-platform
  source:
    repoURL: git@github.com:guilherme-jafar/aws-mini-platform-argocd.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace:  mini-platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

      ## kubectl --kubeconfig ~/.kube/config-aws-mini-platform apply -f apps/app-of-apps.yaml to sync for the first time. After that, ArgoCD will automatically sync the apps defined in this app-of-apps.yaml file.
